insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('abarnetti@adobe.com', 5, 'SCrEen fLicKeRiNg', '1/31/2027');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('abeggan2@house.gov', 5, 'error 0x80002c', '8/16/2028');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 5, 'BSOD', '10/18/2027');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('aoakwell4@people.com.cn', 2, 'bad game?', '12/18/2025');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('cbirkbeckh@amazon.co.jp', 5, 'any mod?', '4/29/2027');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('develynl@webs.com', 1, 'how to clear this game?', '10/9/2029');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('dmccolgan9@pcworld.com', 1, 'hax notepad.txt', '2/26/2024');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('eludfordb@scribd.com', 36, 'corrupted savefile', '7/12/2028');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('flepickk@simplemachines.org', 39, '', '3/7/2030');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('ftallquiste@fc2.com', 26, '', '11/14/2024');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('gcornhillg@un.org', 60, '', '6/7/2027');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('gpoulson8@amazon.co.jp', 35, '', '9/5/2025');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('gsebirej@yandex.ru', 23, '', '4/15/2026');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('jjoire3@example.com', 24, '', '4/8/2024');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('lcahey7@blogspot.com', 25, '', '10/19/2025');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('lmalsher1@usda.gov', 26, '', '5/19/2026');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('mcumeso@princeton.edu', 11, '', '11/26/2024');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('gsebirej@yandex.ru', 12, '', '9/14/2025');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('rarnaudinm@craigslist.org', 13, '', '3/19/2027');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('rladdsd@soundcloud.com', 14, '', '5/7/2029');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('sheathcoatc@phpbb.com', 16, '', '8/28/2030');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('ubengaln@edublogs.org', 15, '', '10/2/2024');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('vwahnerf@nsw.gov.au', 17, '', '10/17/2029');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('winkin5@nature.com', 21, '', '8/5/2027');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('yianelli6@about.com', 22, '', '6/16/2030');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 43, '', '12/16/2027');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 24, '', '2/7/2024');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 14, '', '9/14/2029');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 1, '', '5/1/2028');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 31, '', '6/28/2027');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 32, '', '6/10/2028');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 33, '', '8/24/2027');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 34, '', '12/18/2024');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 35, '', '6/11/2027');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('gpoulson8@amazon.co.jp', 41, '', '2/11/2025');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('eludfordb@scribd.com', 42, '', '1/21/2025');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('abarnetti@adobe.com', 43, '', '4/14/2024');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 44, '', '7/8/2024');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('anarrie0@youtu.be', 45, '', '1/8/2029');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('gsebirej@yandex.ru', 46, '', '12/15/2026');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('abarnetti@adobe.com', 47, '', '6/29/2029');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('gsebirej@yandex.ru', 48, '', '5/12/2026');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('sheathcoatc@phpbb.com', 49, '', '7/21/2029');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('gpoulson8@amazon.co.jp', 20, '', '1/1/2026');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('abarnetti@adobe.com', 1, '', '10/16/2026');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('lmalsher1@usda.gov', 11, '', '8/9/2029');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('ubengaln@edublogs.org', 12, '', '2/11/2024');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('vwahnerf@nsw.gov.au', 15, '', '4/15/2027');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('winkin5@nature.com', 16, '', '4/21/2024');
insert into forum (email_user, id_aplikasi, judul, waktu_pembuatan) values ('yianelli6@about.com', 29, '', '8/30/2026');